### ISSUE TITLE
Issues with ArtificialCrowdedFieldPSFPhotometry.ipynb

### ISSUE THREAD

**Issue by vkaustubh** [astropy/photutils-datasets#14]
Hi!

Me and a colleague are trying to get a feel for the package so that we can use it for an upcoming data analysis. We decided to study the ArtificialCrowdedFieldPSFPhotometry.ipynb tutorial. What we have essentially done is

- installed the relevant packages
- copy pasted the code from various cells to get a .py file
- and run it

Our code:
`
from photutils.detection import DAOStarFinder, IRAFStarFinder
from photutils.psf import DAOGroup
from photutils.psf import IntegratedGaussianPRF
from photutils.background import MMMBackground
from photutils.background import MADStdBackgroundRMS
from astropy.modeling.fitting import LevMarLSQFitter
from astropy.stats import gaussian_sigma_to_fwhm

import numpy as np
import photutils
from collections import OrderedDict
from photutils.datasets import make_random_gaussians_table
n_sources = 5
param_ranges = [('amplitude', [500, 1000]),
                ('x_mean', [0, 500]),
                ('y_mean', [0, 300]),
                ('x_stddev', [1, 5]),
                ('y_stddev', [1, 5]),
                ('theta', [0, np.pi])]
param_ranges = OrderedDict(param_ranges)
sources = make_random_gaussians_table(n_sources, param_ranges,
                                      random_state=12345)
print(sources)

from photutils.datasets import make_gaussian_sources_image
from photutils.datasets import make_noise_image

shape = (256, 256)
image01 = make_gaussian_sources_image(shape, sources)   
image02 = make_noise_image(shape, type='poisson', mean=6., random_state=123)
image03 = make_noise_image(shape, type='gaussian', mean=0., stddev=2., random_state=123)
image = image01 + image02 + image03

bkgrms = MADStdBackgroundRMS()
std = bkgrms(image)

sigma_psf = 2.0
iraffind = IRAFStarFinder(threshold=3.5*std,
                          fwhm=sigma_psf*gaussian_sigma_to_fwhm,
                          minsep_fwhm=0.01, roundhi=5.0, roundlo=-5.0,
                          sharplo=0.0, sharphi=2.0)

daogroup = DAOGroup(2.0*sigma_psf*gaussian_sigma_to_fwhm)
mmm_bkg = MMMBackground()
psf_model = IntegratedGaussianPRF(sigma=[1, 5])

fitter = LevMarLSQFitter()

from photutils.psf import IterativelySubtractedPSFPhotometry

photometry = IterativelySubtractedPSFPhotometry(finder=iraffind, group_maker=daogroup,
                                                bkg_estimator=mmm_bkg, psf_model=psf_model,
                                                fitter=LevMarLSQFitter(),
                                                niters=2, fitshape=11,
                                                aperture_radius=5.0)
result_tab = photometry(image)
residual_image = photometry.get_residual_image()
`

And running this code gives an error.
`
$ python psf005kv001.py 
    amplitude           x_mean             y_mean            x_stddev          y_stddev            theta       
----------------- ------------------ ------------------ ----------------- ------------------ ------------------
 964.808046408574 297.77235148962575 224.31444278138216  3.62564473232908  3.569901311583365  2.292385861762183
658.1877772908929 482.25725986781083  288.3920208218464 4.239250210163739  3.869814483249655 3.1227889206244206
591.9594058385472 326.58854843578547 2.5164893824660473 4.488703654897132  2.870396028877186  2.126461480316531
602.2801392765199 374.45331876695593   31.9333130093158 4.858590389487721 2.3023387101575112 2.4844422123639958
783.8625145408433  326.7849354258677  89.61111413081446 3.894741387679814  2.758578423539238  0.536942976674464
/home/kaustubh/Test/Devraj/psf/venv/lib/python3.6/site-packages/skimage/measure/_moments.py:258: UserWarning: Using deprecated 2D-only, xy-coordinate interface to moments_central. This interface will be removed in scikit-image 0.16. Use moments_central(image, center=(cr, cc), order=3).
  warn(message)
Traceback (most recent call last):
  File "/home/kaustubh/Test/Devraj/psf/venv/lib/python3.6/site-packages/astropy/modeling/core.py", line 3247, in _prepare_inputs_single_model
    broadcast = check_broadcast(input_shape, param.shape)
  File "/home/kaustubh/Test/Devraj/psf/venv/lib/python3.6/site-packages/astropy/utils/misc.py", line 1103, in check_broadcast
    shapes[max_dim_idx], max_dim_idx, shapes[idx], idx)
astropy.utils.misc.IncompatibleShapeError: ((121,), 0, (2,), 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "psf005kv001.py", line 88, in <module>
    result_tab = photometry(image)
  File "/home/kaustubh/Test/Devraj/psf/venv/lib/python3.6/site-packages/astropy/utils/decorators.py", line 488, in wrapper
    return function(*args, **kwargs)
  File "/home/kaustubh/Test/Devraj/psf/venv/lib/python3.6/site-packages/photutils/psf/photometry.py", line 190, in __call__
    return self.do_photometry(image, init_guesses)
  File "/home/kaustubh/Test/Devraj/psf/venv/lib/python3.6/site-packages/astropy/utils/decorators.py", line 488, in wrapper
    return function(*args, **kwargs)
  File "/home/kaustubh/Test/Devraj/psf/venv/lib/python3.6/site-packages/photutils/psf/photometry.py", line 669, in do_photometry
    output_table = self._do_photometry(['x_0', 'y_0', 'flux_0'])
  File "/home/kaustubh/Test/Devraj/psf/venv/lib/python3.6/site-packages/photutils/psf/photometry.py", line 730, in _do_photometry
    self._residual_image, star_groups)
  File "/home/kaustubh/Test/Devraj/psf/venv/lib/python3.6/site-packages/photutils/psf/photometry.py", line 354, in nstar
    image[usepixel])
  File "/home/kaustubh/Test/Devraj/psf/venv/lib/python3.6/site-packages/astropy/modeling/fitting.py", line 178, in wrapper
    return func(self, model, x, y, z=z, **kwargs)
  File "/home/kaustubh/Test/Devraj/psf/venv/lib/python3.6/site-packages/astropy/modeling/fitting.py", line 883, in __call__
    xtol=acc, full_output=True)
  File "/home/kaustubh/Test/Devraj/psf/venv/lib/python3.6/site-packages/scipy/optimize/minpack.py", line 383, in leastsq
    shape, dtype = _check_func('leastsq', 'func', func, x0, args, n)
  File "/home/kaustubh/Test/Devraj/psf/venv/lib/python3.6/site-packages/scipy/optimize/minpack.py", line 27, in _check_func
    res = atleast_1d(thefunc(*((x0[:numinputs],) + args)))
  File "/home/kaustubh/Test/Devraj/psf/venv/lib/python3.6/site-packages/astropy/modeling/fitting.py", line 821, in objective_function
    return np.ravel(model(*args[2: -1]) - meas)
  File "/home/kaustubh/Test/Devraj/psf/venv/lib/python3.6/site-packages/astropy/modeling/core.py", line 382, in __call__
    ('equivalencies', None)])
  File "/home/kaustubh/Test/Devraj/psf/venv/lib/python3.6/site-packages/astropy/modeling/core.py", line 363, in __call__
    return super(cls, self).__call__(*inputs, **kwargs)
  File "/home/kaustubh/Test/Devraj/psf/venv/lib/python3.6/site-packages/astropy/modeling/core.py", line 751, in __call__
    inputs, format_info = self.prepare_inputs(*inputs, **kwargs)
  File "/home/kaustubh/Test/Devraj/psf/venv/lib/python3.6/site-packages/astropy/modeling/core.py", line 1491, in prepare_inputs
    **kwargs)
  File "/home/kaustubh/Test/Devraj/psf/venv/lib/python3.6/site-packages/astropy/modeling/core.py", line 3255, in _prepare_inputs_single_model
    param.name, param.shape))
ValueError: Model input argument 'x' of shape (121,) cannot be broadcast with parameter 'sigma' of shape (2,).

`
I am unable to figure out what is causing this problem. Is it a package version compatibility issue? I am also including the output `pip freeze` below.

astropy==3.0.2
backcall==0.1.0
cloudpickle==0.5.3
cycler==0.10.0
dask==0.17.5
decorator==4.3.0
ipython==6.4.0
ipython-genutils==0.2.0
jedi==0.12.0
kiwisolver==1.0.1
matplotlib==2.2.2
networkx==2.1
numpy==1.14.3
parso==0.2.1
pexpect==4.6.0
photutils==0.4
pickleshare==0.7.4
Pillow==5.1.0
prompt-toolkit==1.0.15
ptyprocess==0.5.2
Pygments==2.2.0
pyparsing==2.2.0
python-dateutil==2.7.3
pytz==2018.4
PyWavelets==0.5.2
scikit-image==0.14.0
scikit-learn==0.19.1
scipy==1.1.0
simplegeneric==0.8.1
six==1.11.0
sklearn==0.0
toolz==0.9.0
traitlets==4.3.2
wcwidth==0.1.7

Any help here is appreciated. Thank you so much in advance.

**Comment by larrybradley** [comment]
@mirca Can you take a look?

**Comment by mirca** [comment]
The problem is on this line:
```
psf_model = IntegratedGaussianPRF(sigma=[1, 5])
```

I think you thought that ``sigma=[1, 5]`` would represent the sigma values in `x` and `y` direction. 
Actually, this is possibly a bug because ``IntegratedGaussianPRF`` represents a 2D circular symmetric gaussian integrated over the spatial dimensions, so the parameter ``sigma`` should be a scalar. 

If you use ``psf_model = IntegratedGaussianPRF(sigma=1)``, it should work. But notice that the sources you are simulating sources with different sigmas in the same image, namely ``sigma=1`` and ``sigma=5``.

**Comment by vkaustubh** [comment]
Yeah, that was it! In hindsight, the issue raised by me is rather silly. Sorry for the trouble. I didn't notice my colleague using two different sigmas in the modified code.

I'll close the issue. Since it was not really an issue with the code, I am not sure what you would want - whether you'd want to delete the issue altogether or simply close it. Either should be okay with me.

**Comment by mirca** [comment]
@vkaustubh It's all good, keep them coming =D
